### ISSUE TITLE
Shameless self-promotion :)

### ISSUE THREAD

**Issue by nccdhelton** [samanL33T/Awesome-Mainframe-Hacking#1]
https://www.youtube.com/watch?v=ZfUBv2Ac29Q

^^^ Here's a talk I gave at Cackalackycon 2019 in Raleigh titled "A Gentle Introduction to Hacking Mainframes"

My sole original contribution to z/OS hacking is figuring out that, if you get root in Unix and backdoor a sysprog's account with your SSH key, you can SSH in as him/her, without having to know their password, and can run privileged `tsocmd` commands and escalate your privs on the MVS side.

**Comment by samanL33T** [comment]
That's awesome.
I've added this to the list.
